internal object DependencyVersion {
    //app level
    const val gradle = "4.0.1"
    const val kotlin = "1.8.21"

    //libs
    const val coreKtx = "1.10.0"
    const val appCompat = "1.6.1"
    const val activityKtx = "1.7.0"
    const val fragmentKtx = "1.5.6"
    const val constraintLayout = "2.0.0-beta8"
    const val navigation = "2.5.3"
    const val workManager = "2.8.1"
    const val room = "2.5.1"
    const val lifecycle = "2.6.1"
    const val dagger = "2.44.2"
    const val timberAndroid = "5.0.1"
    const val timberJdk = "5.0.0-SNAPSHOT"
    const val material = "1.9.0"
    const val firebaseBom = "32.1.1"
    const val firebaseAnalyticsKtx = "21.3.0"
    const val coroutinesTest = "1.6.4"
    const val coroutinesAndroid = "1.7.0"
    const val androidAnnotation = "1.6.0"
    const val jvmAnnotation = "1.6.0"
    const val hilt = "2.44"
    const val hiltWorkManager = "1.0.0"
    const val hiltAndroidCompiler = "1.0.0"
    const val hiltNavigation = "1.0.0"
    const val gson = "2.10.1"
    const val preference = "1.2.0"

    //test
    const val junit4 = "4.13.2"
    const val junit5Jupiter = "5.9.3"
    const val junit5Platform = "1.9.3"
    const val testRunner = "1.5.2"
    const val testRules = "1.5.0"
    const val extJunit = "1.1.5"
    const val extJunitKtx = "1.1.5"
    const val espresso = "3.5.1"
    const val fragmentTesting = "1.5.6"
    const val conditionWatcher = "0.2"
}
